steps:
- id: checkout
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/asmith60/node-hapi-typescript-template.git']
- id: install
  name: 'circleci/node:10.8'
  args: ['npm', 'install']
- id: build
  name: 'circleci/node:10.8'
  args: ['npm', 'run', 'build']
- id: unit-test
  name: 'circleci/node:10.8'
  args: ['npm', 'run', 'test:junit']
  waitFor: ['build']
- id: lint-test
  name: 'circleci/node:10.8'
  args: ['npm', 'run', 'test:lint']
  waitFor: ['build']
- id: security-test
  name: 'circleci/node:10.8'
  args: ['npm', 'run', 'test:security']
  waitFor: ['build']
