steps:
- id: checkout
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/asmith60/node-hapi-typescript-template.git']
- id: install
  name: 'gcr.io/cloud-builders/npm:node-10.3.0'
  args: ['install']
- id: build
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- id: unit-test
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:junit']
  waitFor: ['build']
- id: lint-test
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:lint']
  waitFor: ['build']
- id: security-test
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:security']
  waitFor: ['build']
