steps:
- id: checkout
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/asmith60/node-hapi-typescript-template.git']
- id: install
  name: 'gcr.io/cloud-builders/npm:node-10.3.0'
  args: ['install']
- id: build
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- id: pwd
  name: 'alpine:latest'
  args: ['pwd']
- id: ls
  name: 'alpine:latest'
  args: ['ls -l']
- id: cd
  name: 'alpine:latest'
  args: ['cd ..', '&&', 'ls -l']
