steps:
# - id: checkout
#   name: 'gcr.io/cloud-builders/git'
#   args: ['clone', 'https://github.com/asmith60/node-hapi-typescript-template.git']
# - id: unshallow
#   name: 'alpine:latest'
#   args: ['pwd']
# - id: status
#   name: 'alpine:latest'
#   args: ['ls']
- id: install
  name: 'gcr.io/cloud-builders/npm:node-10.3.0'
  args: ['install']
- id: build
  name: 'gcr.io/cloud-builders/npm:node-10.3.0'
  args: ['run', 'build']
- id: unit-test
  name: 'gcr.io/cloud-builders/npm:node-10.3.0'
  args: ['run', 'test:junit']
  waitFor: ['build']
- id: lint-test
  name: 'gcr.io/cloud-builders/npm:node-10.3.0'
  args: ['run', 'test:lint']
  waitFor: ['build']
- id: security-test
  name: 'gcr.io/cloud-builders/npm:node-10.3.0'
  args: ['run', 'test:security']
  waitFor: ['build']
- id: release
  name: 'gcr.io/cloud-builders/npm:node-10.3.0'
  args: ['run', 'release']
  waitFor: ['unit-test', 'lint-test', 'security-test']
