version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-debug
    command: run debug
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
      - "9222:9222"
