version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - dist
  unit-test:
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          when: always
          command: npm run test:junit
      - store_test_results:
          path: ./artifacts/junit
      - store_artifacts:
          path: ./artifacts
  lint-test:
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm run lint:junit
      - store_test_results:
          path: ./artifacts/junit
      - store_artifacts:
          path: ./artifacts
  security-test:
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir -p artifacts/security/nsp
            npm --loglevel=silent run test:security -- --reporter json | tee artifacts/security/nsp/security-test-results.json
      - store_artifacts:
          path: ./artifacts

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - lint-test:
          requires:
            - build
      - security-test:
          requires:
            - build
